### ISSUE TITLE
django-shop

### ISSUE THREAD

**Issue by i25** [divio/django-shop#294]
OperationalError at /shop/products/

no such table: shop_product

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/shop/products/
Django Version: 	1.8.5
Exception Type: 	OperationalError
Exception Value: 	

no such table: shop_product

Exception Location: 	/home/pradeep/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
Python Executable: 	/usr/bin/python2.7
Python Version: 	2.7.6
Python Path: 	

['/home/pradeep/Desktop/srit',
 '/usr/local/lib/python2.7/dist-packages/setuptools-5.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg',
 '/home/pradeep/Desktop/srit',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/home/pradeep/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

Server time: 	Wed, 25 Nov 2015 08:33:43 +0000
Error during template rendering

In template /home/pradeep/.local/lib/python2.7/site-packages/shop/templates/shop/product_list.html, error at line 7

**Comment by atheiste** [comment]
Hi, I'd suggest to try to tackle this a bit on your own. Did you even do migration? If it is a problem which you cannot overcome then please include what you tried. This is not a commercial support. This is developer's forum where people spend their free time. So please take this into account and try to be more humble and helpful.

**Comment by i25** [comment]
thanks atheiste that works
